### PR TITLE
Use single number system

### PR DESCRIPTION
**Pull request by mahnunchik**
This PR is just a clarification for somebody who are reading the code.

### CODE REVIEW

**Comment by mahnunchik** [comment]
Hi @ashisherc I thought it is just a clarification but it seems it is **breaking change**, many tests fails. I didn't fix them to show you the issue.

By specification:
* https://github.com/LedgerHQ/orakolo/blob/master/papers/Ed25519_BIP%20Final.pdf
* https://www.rfc-editor.org/rfc/rfc8032#section-5.1.5

> The lowest three bits of the first octet are cleared, the highest bit of the last octet is cleared, and the second highest bit of the last octet is set.

image

```
xprv[31] &= 0x1f;
// is equal
xprv[31] &= 0b00011111;
```
Current implementation clears **third highest** bit: 0b00**0**11111

More comments in PR code.

It seems @fix was right here: https://github.com/StricaHQ/bip32ed25519/issues/3

**Comment by ashisherc** [comment]
The implementation follows the Bip32Ed25519 paper, please see this https://github.com/StricaHQ/bip32ed25519/issues/3#issuecomment-1152974216 for the explanation

**Comment by mahnunchik** [comment]
@ashisherc please read the specification carefully. You had mixed up highest and lowest bits in your explanation in the comment https://github.com/StricaHQ/bip32ed25519/issues/3#issuecomment-1152974216

**Comment by ashisherc** [comment]
hm, are you saying the implementation deviates from the standard?

**Comment by mahnunchik** [comment]
Yes, there is two documents saying the same but a bit in different words.

* https://github.com/LedgerHQ/orakolo/blob/master/papers/Ed25519_BIP%20Final.pdf
* https://www.rfc-editor.org/rfc/rfc8032#section-5.1.5

```
11111111 11111111 11111111 11111111 11111111 11111111 11111111 11111111
// 1) The lowest three bits of the first octet are cleared
& 11111000
// 2) the highest bit of the last octet is cleared
11111000 11111111 11111111 11111111 11111111 11111111 11111111 11111111
                                                             & 00111111 or
                                                             & 01111111
// 3) the second highest bit of the last octet is set
                                                             | 01000000
11111000 11111111 11111111 11111111 11111111 11111111 11111111 01111111
```

Current implementation makes `& 00011111` on step 2. So third highest bit is cleared.

**Comment by mahnunchik** [comment]
https://github.com/LedgerHQ/orakolo/blob/master/papers/Ed25519_BIP%20Final.pdf

> If the third highest bit of the last byte of kL is not zero, **discard k**.

So the key must be discarded, not byte manually cleared.

**Comment by ashisherc** [comment]
You are misunderstanding the para in section V->A. Please read the bip32ed25519 specs carefully. The implementation of this library follows the specs accurately and is the standard way Cardano keypairs are generated, this implementation is in line with the specs and other language implementations as well (Haskell, Rust, C)

**Comment by fix** [comment]
back to this after a while. Might be the Cardano implementation has deviated from the spec in this.

Point is the following: The security of the implementation might be at stake, since the byte clearing is done to prevent from 8-malleability of ed25519 curve. I am not a specialist but it might be possible then to forge another valid signature from an existing signature without knowing the private key.

**Comment by ashisherc** [comment]
@fix would recommend reaching out to the author of the bip32-ed25519 spec (link in the chat above) as the doubt you have is not related to this library but the spec itself :)

**Pull request closed without merging**
